services:
  # ---------------------------------------------------------------
  # Free Games Claimer Remaster
  # ---------------------------------------------------------------
  app:
    # To run the experimental development build, set FGC_TAG=dev in your .env file!
    image: ghcr.io/p-adamiec/free-games-claimer-remaster:${FGC_TAG:-latest}
    container_name: fgc-remaster
    build: .
    restart: unless-stopped
    tty: true
    stdin_open: true
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '0.5'
          memory: 512M
    ports:
      - "${NOVNC_PORT:-7080}:7080"
    volumes:
      - fgc_data:/fgc/data
    env_file:
      - .env

volumes:
  fgc_data:
